### PR TITLE
update typos

### PR DESCRIPTION
**Pull request by kokonut27**
* repl.it => replit.com
* grammar :D

### CODE REVIEW

**Comment by Coding-Cactus** [comment]
repl.it still goes to replit.com

**Comment by kokonut27** [comment]
> repl.it still goes to replit.com

I know, but I just felt like editing the links in addition to editing the text from repl.it to replit.com (the links were just added on - the main priority was the text change)

**Comment by Coding-Cactus** [comment]
In the case of changing the text references from Repl.it, would it make more sense to change them to just Replit, as that is the actual brand name?

**Comment by kokonut27** [comment]
Hmm, yeah, I think that might be a better idea - want me to change that for you? Or are you just gonna create a commit for that?

**Comment by Coding-Cactus** [comment]
You can change that, and I'll accept the replit.com url changes.

**Comment by kokonut27** [comment]
Done :) 

Feel free to review them and edit any commits of mine.

**Review by Coding-Cactus — APPROVED** [review]

**Pull request merged**
